//
//  MainpageViewController.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainpageViewController: UIViewController
{
  var interactor: MainpageBusinessLogic?
  var router: (NSObjectProtocol & MainpageRoutingLogic & MainpageDataPassing)?

//    MARK: -IBOutlet Property
    
    
    @IBOutlet weak var temTitleLabel: UILabel! {
        didSet {
            temTitleLabel.text = "28/38"
        }
    }
    
    
    @IBOutlet weak var weatherTableView: UITableView! {
        didSet {
            weatherTableView.delegate = self
            weatherTableView.dataSource = self
        }
    }
    
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = MainpageInteractor()
    let presenter = MainpagePresenter()
    let router = MainpageRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Mainpage.Something.Request()
    interactor?.doSomething(request: request)
  }
  
}

protocol MainpageDisplayLogic: class
{
  func displaySomething(viewModel: Mainpage.Something.ViewModel)
}

extension MainpageViewController: MainpageDisplayLogic {
    
    func displaySomething(viewModel: Mainpage.Something.ViewModel)
    {
      //nameTextField.text = viewModel.name
    }
}

//MARK: -DataSource and Delegate TableView

extension MainpageViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 7
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return UITableViewCell()
    }
    
    
}
