//
//  MainpageModels.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Mainpage
{
  // MARK: Use cases
  
    enum FetchWeatherModel {
        struct Request {
            
        }
        
        struct Response {
            var status: NetworkStatus
        }
        
        struct ViewModel {
            var status: NetworkStatus
        }
    }
    
    enum GetWeatherDaily {
        
        struct Request {
            
        }
        
        struct Response {
            var dateName: [String] = []
            var shortDate: [String] = []
            var minTemp: [String] = []
            var maxTemp: [String] = []
            var unitTemp: String = ""
        }
        
        struct ViewModel {
            var dateName: [String] = []
            var shortDate: [String] = []
            var minTemp: [String] = []
            var maxTemp: [String] = []
            var unitTemp: String = ""
        }
    }
    
    enum SelectWeatherDate {
        struct Request {
            var index: Int
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
 
}
