//
//  MainpagePresenter.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainpagePresentationLogic
{
    func fetchedWeather(response: Mainpage.FetchWeatherModel.Response)
}

class MainpagePresenter: MainpagePresentationLogic
{
  weak var viewController: MainpageDisplayLogic?
  
  // MARK: Do something
  
    func fetchedWeather(response: Mainpage.FetchWeatherModel.Response) {
        let viewModel = Mainpage.FetchWeatherModel.ViewModel(status: response.status)
        viewController?.displayFetchedWeather(viewModel: viewModel)
    }
    

}
