//
//  MainpageInteractor.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainpageBusinessLogic
{
  func doSomething(request: Mainpage.Something.Request)
}

protocol MainpageDataStore
{
  //var name: String { get set }
}

class MainpageInteractor: MainpageBusinessLogic, MainpageDataStore
{
  var presenter: MainpagePresentationLogic?
  var worker: MainpageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Mainpage.Something.Request)
  {
    worker = MainpageWorker()
    worker?.doSomeWork()
    
    let response = Mainpage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
