//
//  MainpageRouter.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainpageRoutingLogic
{
    func routeToSelectDateWeather()
}

protocol MainpageDataPassing
{
  var dataStore: MainpageDataStore? { get }
}

class MainpageRouter: NSObject, MainpageRoutingLogic, MainpageDataPassing
{
  weak var viewController: MainpageViewController?
  var dataStore: MainpageDataStore?
  
  // MARK: Routing
  
    func routeToSelectDateWeather() {
        let destinationVC = SelectDateWeatherViewController(nibName: "SelectDateWeather", bundle: nil)
        var destinationDS = destinationVC.router!.dataStore!
        passToSelectDateWeather(source: dataStore!, destination: &destinationDS)
        navigationToSelectDateWeather(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
  
    func navigationToSelectDateWeather(source: MainpageViewController, destination: SelectDateWeatherViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
  
  // MARK: Passing data
  
    func passToSelectDateWeather(source: MainpageDataStore, destination: inout SelectDateWeatherDataStore) {
        destination.titleDate = source.titleDate
        destination.timeArray = source.timeArray
        destination.tempUnit = source.tempUnit
        destination.tempArray = source.tempArray
    }
}
