//
//  MainpageInteractor.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainpageBusinessLogic
{
    func fetchWeather(request: Mainpage.FetchWeatherModel.Request)
    func getWeatherDaily(request: Mainpage.GetWeatherDaily.Request)
    func selectWeatherDate(request: Mainpage.SelectWeatherDate.Request)
}

protocol MainpageDataStore
{
  //var name: String { get set }
    var titleDate: String { get set }
    var timeArray: [String] { get set }
    var tempArray: [String] { get set }
    var tempUnit: String { get set }
}

class MainpageInteractor: MainpageBusinessLogic, MainpageDataStore
{
    var presenter: MainpagePresentationLogic?
    var worker: MainpageWorker?
    let network = NetworkAPI()
    var allData: WeatherModel?
    var titleDate: String = ""
    var timeArray: [String] = []
    var tempArray: [String] = []
    var tempUnit: String = ""
    //var name: String = ""
    
    // MARK: Do something
    
    
    func fetchWeather(request: Mainpage.FetchWeatherModel.Request) {
        
        network.callGetWeatherAPI { result in
            switch result {
            case .success(let data):
                self.allData = data
                let response = Mainpage.FetchWeatherModel.Response(status: .success)
                self.presenter?.fetchedWeather(response: response)
            case .failure(let failure):
                let response = Mainpage.FetchWeatherModel.Response(status: .failure(failure))
                self.presenter?.fetchedWeather(response: response)
            }
        }
    }
    
    func getWeatherDaily(request: Mainpage.GetWeatherDaily.Request) {
        let weatherDate = WeatherDate()
        let sumDateString = weatherDate.formatDateString(dates: self.allData?.daily.time ?? [])
        let minTemp = self.allData?.daily.temperature2MMin.map { String($0)}
        let maxTemp = self.allData?.daily.temperature2MMax.map { String($0)}
        let response = Mainpage.GetWeatherDaily.Response(dateName: sumDateString.dateName,
                                                         shortDate: sumDateString.shortDate,
                                                         minTemp: minTemp ?? [],
                                                         maxTemp: maxTemp ?? [],
                                                         unitTemp: self.allData?.dailyUnits.temperature2MMax ?? "")
        self.presenter?.presentGetWeatherDaily(response: response)
    }
    
    func selectWeatherDate(request: Mainpage.SelectWeatherDate.Request) {
        let selectDate = self.allData?.daily.time[request.index] ?? ""
        let weatherDate = WeatherDate()
        var startTemp = request.index * 24
        var stopTemp = 0
        var timeFilter: [String] = []
        if request.index != 0 {
            stopTemp = (request.index * 24) - 1
        } else {
            stopTemp = 23
        }
        titleDate = weatherDate.formatDateTitle(date: selectDate)
        for i in startTemp...stopTemp {
            timeFilter.append(String(self.allData?.hourly.time[i] ?? ""))
            tempArray.append(String(self.allData?.hourly.temperature2M[i] ?? 0.0))
        }
        timeArray = weatherDate.getTimeDate(dates: timeFilter)
        tempUnit = self.allData?.hourlyUnits.temperature2M ?? ""
        let response = Mainpage.SelectWeatherDate.Response()
        self.presenter?.presentSelectWeatherDate(response: response)
    }
    
}
