//
//  SelectDateWeatherPresenter.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectDateWeatherPresentationLogic
{
  func presentSomething(response: SelectDateWeather.Something.Response)
}

class SelectDateWeatherPresenter: SelectDateWeatherPresentationLogic
{
  weak var viewController: SelectDateWeatherDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SelectDateWeather.Something.Response)
  {
    let viewModel = SelectDateWeather.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
