//
//  SelectDateWeatherModels.swift
//  WeatherApp
//
//  Created by Paul on 3/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SelectDateWeather
{
  // MARK: Use cases
  
    enum GetDataToDisplay {
        struct Request {
            
        }
        
        struct Response {
            var dataDisplay: DisplayWeatherTimeModel
        }
        
        struct ViewModel {
            var dataDisplay: DisplayWeatherTimeModel
        }
    }
}
